name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      # - name: Install Node 16
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "16"

      # - name: Build Razor CSS
      #   run: dotnet build ./StaticWebAppsDemo/BlazorWasm -c Release

      # - name: Build Tailwind CSS
      #   run: |
      #     cd ./StaticWebAppsDemo/
      #     npm install -g npm@latest
      #     npm install
      #     npm run publish-wasm

      # - name: Publish Site
      #   run: dotnet publish ./StaticWebAppsDemo/BlazorWasm -c Release

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # api_build_command: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -runtime dotnet --version 3.1
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_SKY_006AF1D1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          # app_location: "./StaticWebAppsDemo/BlazorWasm/bin/Release/publish/wwwroot" # App source code path
          app_location: "./StaticWebAppsDemo/BlazorWasm/" # App source code path
          api_location: "./StaticWebAppsDemo/FunctionsAPI" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_SKY_006AF1D1E }}
          action: "close"
